name: Deploy Serverless

on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
      - name: cache backend build
        uses: actions/cache@v2
        with:
          path: |
            ./backend/target
            ./backend/serverless.yml
          key: ${{ runner.os }}-$GITHUB_RUN_ID
  deploy:
    needs: build_backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch Cache Backend Build
        uses: actions/cache@v2
        with:
          path: |
            ./backend/target
            ./backend/serverless.yml
          key: ${{ runner.os }}-$GITHUB_RUN_ID

      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: -c "cd ./backend && serverless deploy --stage dev"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

